import { ArbitrageItem, DevExGoal } from '@/types/gamevault';

export const INITIAL_ARBITRAGE_ITEMS: ArbitrageItem[] = [
  {
    id: 'arb-01',
    name: 'Rayman 1000 Gloves',
    game: 'GROWTOPIA',
    buyLocation: 'World BUYRAYMAN (Wholesale)',
    buyPrice: 3400,
    sellLocation: 'World SELLRAYMAN (Retail)',
    sellPrice: 3680,
    taxRatePercent: 0,
    unitName: 'DL',
    trend: 'BULLISH',
    weeklyChangePercent: 5.4,
    notes: 'Item koleksi langka. Selisih harga tinggi saat weekend malam.',
  },
  {
    id: 'arb-02',
    name: 'Magplant 5000 Remote',
    game: 'GROWTOPIA',
    buyLocation: 'World BUYMAG / Discord Trade',
    buyPrice: 2750,
    sellLocation: 'World SELLMAG / INDO TRADE',
    sellPrice: 2920,
    taxRatePercent: 0,
    unitName: 'DL',
    trend: 'STABLE',
    weeklyChangePercent: 1.2,
    notes: 'Kebutuhan farmer BFG konstan. Likuiditas cepat cair dalam 2 jam.',
  },
  {
    id: 'arb-03',
    name: 'Laser Grid Seeds (Full World 2.640x)',
    game: 'GROWTOPIA',
    buyLocation: 'World BUYGRID (Borongan)',
    buyPrice: 13.2,
    sellLocation: 'World SEEDSHOP (Eceran)',
    sellPrice: 15.0,
    taxRatePercent: 0,
    unitName: 'DL',
    trend: 'BULLISH',
    weeklyChangePercent: 3.8,
    notes: 'Beli paket borongan 2640 bibit, jual per 200 bibit dengan margin untung 1.8 DL.',
  },
  {
    id: 'arb-04',
    name: 'Valkyrie Helm (Limited UGC Edition)',
    game: 'ROBLOX',
    buyLocation: 'Trade Hangout Plaza (Bargain)',
    buyPrice: 42000,
    sellLocation: 'Roblox Marketplace (Listing)',
    sellPrice: 65000,
    taxRatePercent: 30,
    unitName: 'Robux',
    trend: 'BULLISH',
    weeklyChangePercent: 8.7,
    notes: 'Net jual: 45.500 R$ (setelah pajak 30%). Bersih profit: +3.500 R$.',
  },
  {
    id: 'arb-05',
    name: 'Super Super Happy Face (SSHF)',
    game: 'ROBLOX',
    buyLocation: 'Discord Rolimons Arbitrage',
    buyPrice: 110000,
    sellLocation: 'Marketplace Instant Liquidity',
    sellPrice: 165000,
    taxRatePercent: 30,
    unitName: 'Robux',
    trend: 'BULLISH',
    weeklyChangePercent: 12.1,
    notes: 'Net jual: 115.500 R$. Profit bersih dev: +5.500 Robux.',
  },
  {
    id: 'arb-06',
    name: 'Diamond Dragon (Pet)',
    game: 'GROWTOPIA',
    buyLocation: 'World BUYDRAGON',
    buyPrice: 810,
    sellLocation: 'World TRADEWORLD',
    sellPrice: 875,
    taxRatePercent: 0,
    unitName: 'DL',
    trend: 'BEARISH',
    weeklyChangePercent: -2.3,
    notes: 'Harga berfluktuasi. Rekomendasi beli hanya di bawah 810 DL.',
  },
];

export const INITIAL_DEVEX_GOALS: DevExGoal[] = [
  {
    id: 'goal-01',
    title: 'Target DevEx Q4 (Pencairan Pertama)',
    targetRobux: 100000,
    currentRobux: 78450,
    createdAt: '2026-09-01',
  },
  {
    id: 'goal-02',
    title: 'Upgrade Workstation M3 Pro (Target $1.500 USD)',
    targetRobux: 430000,
    currentRobux: 215000,
    createdAt: '2026-08-15',
  },
];
